# Generated by Django 2.2.27 on 2022-04-03 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 3, 19, 9, 12, 955876), verbose_name='Опубликована'),
        ),
    ]
