# Generated by Django 3.2.4 on 2022-12-21 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221219_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='price',
            field=models.FloatField(default=100, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 21, 11, 12, 22, 368489), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 21, 11, 12, 22, 368489), verbose_name='Дата комментария'),
        ),
    ]
