# Generated by Django 3.2.4 on 2022-12-24 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20221224_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='employer_id',
            field=models.IntegerField(default=2, verbose_name='ID мастера'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 24, 10, 20, 48, 597245), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 24, 10, 20, 48, 598242), verbose_name='Дата комментария'),
        ),
    ]
