# Generated by Django 3.2.4 on 2022-12-26 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20221224_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 26, 21, 38, 3, 65429), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Путь к картинке'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 26, 21, 38, 3, 66439), verbose_name='Дата комментария'),
        ),
    ]
