# Generated by Django 3.2.4 on 2022-12-26 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20221226_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='bio',
            field=models.TextField(default='Биография', verbose_name='Биография'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='image',
            field=models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к картинке'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 26, 22, 59, 57, 775566), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.FileField(default='temp.jpg', upload_to='', verbose_name='Путь к картинке'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 26, 22, 59, 57, 776585), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='заказано', max_length=100, verbose_name='Статус'),
        ),
    ]
