# Generated by Django 4.2 on 2023-05-01 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_service_basket_delete_shoplist_order_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
        migrations.RemoveField(
            model_name='service_basket',
            name='count',
        ),
        migrations.RemoveField(
            model_name='service_basket',
            name='employer_id',
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 5, 1, 14, 5, 23, 329181), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 5, 1, 14, 5, 23, 329181), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(verbose_name='ID услуги'),
        ),
    ]
